INSERT INTO biblio.EMPRUNTER
(ID_DOCUMENT, CARTE_EMPRUNTEUR, DATE_EMPRUNT, DATE_RETOUR_PREVUE)
VALUES
(1, 1001, CURRENT_DATE, CURRENT_DATE + INTERVAL '15 days'),
(2, 1002, CURRENT_DATE, CURRENT_DATE + INTERVAL '10 days');