INSERT INTO biblio.TYPE_DOCUMENT (NOM_TYPE_DOCUMENT, CREATED_AT_TYPE_DOCUMENT)
VALUES
('Livre', CURRENT_DATE),
('Magazine', CURRENT_DATE),
('BD', CURRENT_DATE),
('Manuscrit', CURRENT_DATE),
('Thèse', CURRENT_DATE);