INSERT INTO biblio.EMPRUNTEUR
(CARTE_EMPRUNTEUR, NOM_EMPRUNTEUR, PRENOM_EMPRUNTEUR, ADRESSE_RUE_EMPRUNTEUR,
 ATTRIBUT_VILLE_EMPRUNTEUR, ADRESSE_CODEPOSTAL_EMPRUNTEUR, EMAIL_EMPRUNTEUR,
 MOT_DE_PASSE, DEBUT_ABONNEMENT, EXPIRATION_ABONNEMENT, CREATED_AT_EMPRUNTEUR)
VALUES
(1001, 'Martin', 'Paul', '1 rue A', 'Annecy', '74000', 'paul.martin@mail.com',
 'pass1234', CURRENT_DATE, CURRENT_DATE + INTERVAL '1 year', CURRENT_DATE),

(1002, 'Durand', 'Sophie', '2 rue B', 'Lyon', '69002', 'sophie.durand@mail.com',
 'pass5678', CURRENT_DATE, CURRENT_DATE + INTERVAL '1 year', CURRENT_DATE);