INSERT INTO biblio.EVENEMENT
(ID_TYPE_EVENEMENT, ID_BIBLIOTHEQUE, TITRE_EVENEMENT, DATE_DEBUT, DATE_FIN, CREATED_AT_EVENEMENT)
VALUES
(1, 1, 'Lecture Victor Hugo', CURRENT_DATE, CURRENT_DATE + INTERVAL '1 day', CURRENT_DATE),
(2, 2, 'Conférence Camus', CURRENT_DATE, CURRENT_DATE + INTERVAL '1 day', CURRENT_DATE);