INSERT INTO biblio.TYPE_AUTEUR (NOM_TYPE_AUTEUR, CREATED_AT_TYPE_AUTEUR)
VALUES
('Romaniste', CURRENT_DATE),
('Poète', CURRENT_DATE),
('Essayiste', CURRENT_DATE);

INSERT INTO biblio.TYPE_DOCUMENT (NOM_TYPE_DOCUMENT, CREATED_AT_TYPE_DOCUMENT)
VALUES
('Livre', CURRENT_DATE),
('Magazine', CURRENT_DATE),
('Manuscrit', CURRENT_DATE);

INSERT INTO biblio.TYPE_EVENEMENT (NOM_TYPE_EVENT, CREATED_AT_TYPE_EVENEMENT)
VALUES
('Lecture publique', CURRENT_DATE),
('Dédicace', CURRENT_DATE),
('Conférence', CURRENT_DATE);