INSERT INTO biblio.BIBLIOTHEQUE
(NOM_BIBLIOTHEQUE, ADRESSE_RUE_BIBLIOTHEQUE, ADRESSE_VILLE_BIBLIOTHEQUE, ADRESSE_CODEPOSTAL_BIBLIOTHEQUE, HORAIRES_BIBLIOTHEQUE, CREATED_AT_BIBLIOTHEQUE)
VALUES
('Bibliothèque d''Annecy', '12 rue Royale', 'Annecy', '74000', '9h-18h', CURRENT_DATE),
('Bibliothèque de Lyon', '5 place Bellecour', 'Lyon', '69002', '8h-19h', CURRENT_DATE);