INSERT INTO biblio.TYPE_AUTEUR (NOM_TYPE_AUTEUR, CREATED_AT_TYPE_AUTEUR, UPDATED_AT_TYPE_AUTEUR) VALUES
    ('Romancier',     CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Poète',         CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Scénariste',    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Illustrateur',  CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Essayiste',     CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

