INSERT INTO biblio.TYPE_DOCUMENT (NOM_TYPE_DOCUMENT, CREATED_AT_TYPE_DOCUMENT, UPDATED_AT_TYPE_DOCUMENT) VALUES
    ('Roman',              CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Bande dessinée',     CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Documentaire',       CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Revue scientifique', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Manuel scolaire',    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
