INSERT INTO biblio.TYPE_EVENEMENT (NOM_TYPE_EVENT, CREATED_AT_TYPE_EVENEMENT, UPDATED_AT_TYPE_EVENEMENT) VALUES
    ('Conférence',        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Atelier lecture',   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Exposition',        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Dédicace',          CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Club de lecture',   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

